# Uncomment the next line to define a global platform for your project

platform :ios, '17.2'
use_frameworks!
target 'MovieFinderApp' do

  pod 'SwiftLint'
  pod 'Swinject'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.2'
               end
          end
   end
end
